local M = {}

function M.setup(c, theme)
  local set = vim.api.nvim_set_hl

  vim.o.termguicolors = true
  vim.g.colors_name = theme or "leenium"

  local groups = {
    Normal = { fg = c.fg, bg = c.bg },
    NormalNC = { fg = c.fg, bg = c.bg },
    NormalFloat = { fg = c.fg, bg = c.panel },
    FloatBorder = { fg = c.line, bg = c.panel },
    FloatTitle = { fg = c.accent, bg = c.panel, bold = true },
    Cursor = { fg = c.bg, bg = c.fg },
    CursorLine = { bg = c.panel },
    CursorLineNr = { fg = c.fg, bold = true },
    LineNr = { fg = c.muted },
    SignColumn = { bg = c.bg },
    EndOfBuffer = { fg = c.bg, bg = c.bg },
    ColorColumn = { bg = c.panel },
    Conceal = { fg = c.muted },
    Visual = { bg = c.line },
    Search = { fg = c.bg, bg = c.warn },
    IncSearch = { fg = c.bg, bg = c.accent },
    CurSearch = { fg = c.bg, bg = c.cyan },
    MatchParen = { fg = c.accent, bg = c.line, bold = true },
    Pmenu = { fg = c.fg, bg = c.panel },
    PmenuSel = { fg = c.bg, bg = c.accent },
    PmenuSbar = { bg = c.line },
    PmenuThumb = { bg = c.line_strong },
    StatusLine = { fg = c.fg, bg = c.panel },
    StatusLineNC = { fg = c.muted, bg = c.panel },
    WinSeparator = { fg = c.line },
    VertSplit = { fg = c.line },
    TabLine = { fg = c.muted, bg = c.panel },
    TabLineSel = { fg = c.fg, bg = c.bg, bold = true },
    TabLineFill = { bg = c.panel },
    Folded = { fg = c.soft, bg = c.panel },
    FoldColumn = { fg = c.muted, bg = c.bg },
    Directory = { fg = c.cyan },
    Title = { fg = c.cyan, bold = true },
    Question = { fg = c.cyan },
    MoreMsg = { fg = c.cyan },
    WarningMsg = { fg = c.warn },
    ErrorMsg = { fg = c.error, bold = true },
    ModeMsg = { fg = c.bg, bg = c.accent, bold = true },
    NonText = { fg = c.line },
    Whitespace = { fg = c.line },
    SpecialKey = { fg = c.line_strong },

    Comment = { fg = c.muted, italic = true },
    Constant = { fg = c.warn },
    String = { fg = c.sea_bright },
    Character = { fg = c.sea },
    Number = { fg = c.warn },
    Boolean = { fg = c.warn },
    Float = { fg = c.warn_bright },
    Identifier = { fg = c.fg },
    Function = { fg = c.error_soft },
    Statement = { fg = c.accent },
    Conditional = { fg = c.accent },
    Repeat = { fg = c.accent },
    Label = { fg = c.accent },
    Operator = { fg = c.soft },
    Keyword = { fg = c.accent },
    Exception = { fg = c.error_soft },
    PreProc = { fg = c.sea_bright },
    Include = { fg = c.cyan },
    Define = { fg = c.cyan },
    Macro = { fg = c.error_soft },
    PreCondit = { fg = c.orange },
    Type = { fg = c.type },
    StorageClass = { fg = c.accent },
    Structure = { fg = c.type },
    Typedef = { fg = c.type },
    Special = { fg = c.cyan },
    SpecialComment = { fg = c.muted },
    Underlined = { fg = c.cyan, underline = true },
    Todo = { fg = c.bg, bg = c.warn, bold = true },
    Error = { fg = c.error },

    DiagnosticError = { fg = c.error },
    DiagnosticWarn = { fg = c.warn },
    DiagnosticInfo = { fg = c.blue },
    DiagnosticHint = { fg = c.cyan },
    DiagnosticOk = { fg = c.sea },
    DiagnosticUnderlineError = { undercurl = true, sp = c.error },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.warn },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.blue },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.cyan },

    GitSignsAdd = { fg = c.sea },
    GitSignsChange = { fg = c.warn },
    GitSignsDelete = { fg = c.error },

    DiffAdd = { fg = c.sea_bright, bg = c.panel },
    DiffChange = { fg = c.warn, bg = c.panel },
    DiffDelete = { fg = c.error, bg = c.panel },
    DiffText = { fg = c.fg, bg = c.line },

    TelescopeNormal = { fg = c.fg, bg = c.panel },
    TelescopeBorder = { fg = c.line, bg = c.panel },
    TelescopePromptNormal = { fg = c.fg, bg = c.panel },
    TelescopePromptBorder = { fg = c.line_strong, bg = c.panel },
    TelescopePromptPrefix = { fg = c.cyan },
    TelescopeSelection = { fg = c.fg, bg = c.line },
    TelescopeMatching = { fg = c.cyan, bold = true },

    LazyNormal = { fg = c.fg, bg = c.bg },
    LazyButton = { fg = c.fg, bg = c.panel },
    LazyButtonActive = { fg = c.bg, bg = c.accent },
    LazyH1 = { fg = c.bg, bg = c.accent, bold = true },
    LazySpecial = { fg = c.orange },

    NvimTreeNormal = { fg = c.fg, bg = c.panel },
    NvimTreeWinSeparator = { fg = c.line, bg = c.bg },
    NvimTreeRootFolder = { fg = c.accent, bold = true },
    NvimTreeFolderName = { fg = c.accent },
    NvimTreeFolderIcon = { fg = c.accent },
    NvimTreeOpenedFolderName = { fg = c.accent },
    NvimTreeOpenedFolderIcon = { fg = c.accent },
    NvimTreeEmptyFolderName = { fg = c.muted },
    NvimTreeIndentMarker = { fg = c.line },
    NvimTreeGitDirty = { fg = c.warn },
    NvimTreeGitNew = { fg = c.sea },
    NvimTreeGitDeleted = { fg = c.error },
    NvimTreeGitMerge = { fg = c.orange },
    NvimTreeGitRenamed = { fg = c.cyan },
    NvimTreeGitStaged = { fg = c.sea_bright },
    NvimTreeSpecialFile = { fg = c.cyan },
    NvimTreeImageFile = { fg = c.cyan },

    lualine_a_normal = { fg = c.bg, bg = c.accent, bold = true },
    lualine_a_insert = { fg = c.bg, bg = c.sea, bold = true },
    lualine_a_visual = { fg = c.bg, bg = c.orange, bold = true },
    lualine_a_replace = { fg = c.bg, bg = c.error, bold = true },
    lualine_a_command = { fg = c.bg, bg = c.warn, bold = true },
    lualine_a_terminal = { fg = c.bg, bg = c.sea, bold = true },
    lualine_b_normal = { fg = c.fg, bg = c.panel },
    lualine_c_normal = { fg = c.fg, bg = c.bg },
    lualine_x_normal = { fg = c.muted, bg = c.bg },
    lualine_y_normal = { fg = c.fg, bg = c.panel },
    lualine_z_normal = { fg = c.bg, bg = c.cyan, bold = true },

    ["@comment"] = { fg = c.muted, italic = true },
    ["@keyword"] = { fg = c.accent },
    ["@keyword.function"] = { fg = c.accent },
    ["@keyword.operator"] = { fg = c.accent },
    ["@keyword.return"] = { fg = c.accent },
    ["@string"] = { fg = c.sea_bright },
    ["@string.regex"] = { fg = c.cyan },
    ["@number"] = { fg = c.warn },
    ["@type"] = { fg = c.type },
    ["@type.builtin"] = { fg = c.type },
    ["@type.definition"] = { fg = c.type },
    ["@namespace"] = { fg = c.soft },
    ["@module"] = { fg = c.soft },
    ["@function"] = { fg = c.error_soft },
    ["@function.builtin"] = { fg = c.cyan },
    ["@function.method"] = { fg = c.error_soft },
    ["@function.macro"] = { fg = c.error_soft },
    ["@constructor"] = { fg = c.type },
    ["@variable"] = { fg = c.fg },
    ["@variable.builtin"] = { fg = c.cyan },
    ["@variable.parameter"] = { fg = c.fg },
    ["@variable.member"] = { fg = c.cyan },
    ["@property"] = { fg = c.cyan },
    ["@attribute"] = { fg = c.cyan },
    ["@operator"] = { fg = c.soft },
    ["@punctuation"] = { fg = c.muted },
    ["@punctuation.bracket"] = { fg = c.muted },
    ["@punctuation.delimiter"] = { fg = c.muted },
    ["@punctuation.special"] = { fg = c.cyan },
    ["@lsp.type.namespace"] = { fg = c.soft },
    ["@lsp.type.class"] = { fg = c.type },
    ["@lsp.type.enum"] = { fg = c.type },
    ["@lsp.type.interface"] = { fg = c.cyan },
    ["@lsp.type.struct"] = { fg = c.type },
    ["@lsp.type.type"] = { fg = c.type },
    ["@lsp.type.parameter"] = { fg = c.fg },
    ["@lsp.type.variable"] = { fg = c.fg },
    ["@lsp.type.property"] = { fg = c.cyan },
    ["@lsp.type.enumMember"] = { fg = c.warn },
    ["@lsp.type.function"] = { fg = c.error_soft },
    ["@lsp.type.method"] = { fg = c.error_soft },
    ["@lsp.type.macro"] = { fg = c.error_soft },
    ["@lsp.type.keyword"] = { fg = c.accent },
    ["@lsp.type.comment"] = { fg = c.muted, italic = true },
    ["@lsp.type.string"] = { fg = c.sea_bright },
    ["@lsp.type.number"] = { fg = c.warn },
    ["@lsp.type.regexp"] = { fg = c.cyan },
    ["@lsp.type.operator"] = { fg = c.soft },
    ["@lsp.type.decorator"] = { fg = c.orange },
    ["@lsp.typemod.function.defaultLibrary"] = { fg = c.cyan },
    ["@lsp.typemod.type.defaultLibrary"] = { fg = c.type },
    ["@lsp.typemod.variable.readonly"] = { fg = c.cyan },
    ["@lsp.typemod.property.readonly"] = { fg = c.cyan },
  }

  for group, opts in pairs(groups) do
    set(0, group, opts)
  end
end

return M
