local M = {}

function M.setup(c)
  local set = vim.api.nvim_set_hl

  vim.o.termguicolors = true
  vim.g.colors_name = "leenium"

  local groups = {
    Normal = { fg = c.fg, bg = c.bg },
    NormalNC = { fg = c.fg, bg = c.bg },
    NormalFloat = { fg = c.fg, bg = c.panel },
    FloatBorder = { fg = c.line, bg = c.panel },
    FloatTitle = { fg = c.accent, bg = c.panel, bold = true },
    Cursor = { fg = c.bg, bg = c.fg },
    CursorLine = { bg = c.panel },
    CursorLineNr = { fg = c.fg, bold = true },
    LineNr = { fg = c.muted },
    SignColumn = { bg = c.bg },
    EndOfBuffer = { fg = c.bg, bg = c.bg },
    ColorColumn = { bg = c.panel },
    Conceal = { fg = c.muted },
    Visual = { bg = c.line },
    Search = { fg = c.bg, bg = c.warn },
    IncSearch = { fg = c.bg, bg = c.accent },
    CurSearch = { fg = c.bg, bg = c.accent_bright },
    MatchParen = { fg = c.accent, bg = c.line, bold = true },
    Pmenu = { fg = c.fg, bg = c.panel },
    PmenuSel = { fg = c.bg, bg = c.accent },
    PmenuSbar = { bg = c.line },
    PmenuThumb = { bg = c.line_strong },
    StatusLine = { fg = c.fg, bg = c.panel },
    StatusLineNC = { fg = c.muted, bg = c.panel },
    WinSeparator = { fg = c.line },
    VertSplit = { fg = c.line },
    TabLine = { fg = c.muted, bg = c.panel },
    TabLineSel = { fg = c.fg, bg = c.bg, bold = true },
    TabLineFill = { bg = c.panel },
    Folded = { fg = c.soft, bg = c.panel },
    FoldColumn = { fg = c.muted, bg = c.bg },
    Directory = { fg = c.accent },
    Title = { fg = c.accent, bold = true },
    Question = { fg = c.accent },
    MoreMsg = { fg = c.accent },
    WarningMsg = { fg = c.warn },
    ErrorMsg = { fg = c.error, bold = true },
    ModeMsg = { fg = c.sea },
    NonText = { fg = c.line },
    Whitespace = { fg = c.line },
    SpecialKey = { fg = c.line_strong },

    Comment = { fg = c.muted, italic = true },
    Constant = { fg = c.warn },
    String = { fg = c.sea },
    Character = { fg = c.sea },
    Number = { fg = c.warn },
    Boolean = { fg = c.warn },
    Float = { fg = c.warn },
    Identifier = { fg = c.soft },
    Function = { fg = c.fg },
    Statement = { fg = c.accent },
    Conditional = { fg = c.accent },
    Repeat = { fg = c.accent },
    Label = { fg = c.accent },
    Operator = { fg = c.soft },
    Keyword = { fg = c.accent },
    Exception = { fg = c.error_soft },
    PreProc = { fg = c.accent_bright },
    Include = { fg = c.accent_bright },
    Define = { fg = c.accent_bright },
    Macro = { fg = c.accent_bright },
    PreCondit = { fg = c.accent_bright },
    Type = { fg = c.soft },
    StorageClass = { fg = c.accent },
    Structure = { fg = c.soft },
    Typedef = { fg = c.soft },
    Special = { fg = c.sea },
    SpecialComment = { fg = c.soft },
    Underlined = { fg = c.sea, underline = true },
    Todo = { fg = c.bg, bg = c.warn, bold = true },
    Error = { fg = c.error },

    DiagnosticError = { fg = c.error },
    DiagnosticWarn = { fg = c.warn },
    DiagnosticInfo = { fg = c.sea },
    DiagnosticHint = { fg = c.soft },
    DiagnosticOk = { fg = c.accent_bright },
    DiagnosticUnderlineError = { undercurl = true, sp = c.error },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.warn },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.sea },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.soft },

    GitSignsAdd = { fg = c.accent },
    GitSignsChange = { fg = c.warn },
    GitSignsDelete = { fg = c.error },

    DiffAdd = { fg = c.accent_bright, bg = c.panel },
    DiffChange = { fg = c.warn, bg = c.panel },
    DiffDelete = { fg = c.error, bg = c.panel },
    DiffText = { fg = c.fg, bg = c.line },

    TelescopeNormal = { fg = c.fg, bg = c.panel },
    TelescopeBorder = { fg = c.line, bg = c.panel },
    TelescopePromptNormal = { fg = c.fg, bg = c.panel },
    TelescopePromptBorder = { fg = c.line_strong, bg = c.panel },
    TelescopePromptPrefix = { fg = c.accent },
    TelescopeSelection = { fg = c.fg, bg = c.line },
    TelescopeMatching = { fg = c.accent_bright, bold = true },

    LazyNormal = { fg = c.fg, bg = c.bg },
    LazyButton = { fg = c.fg, bg = c.panel },
    LazyButtonActive = { fg = c.bg, bg = c.accent },
    LazyH1 = { fg = c.bg, bg = c.accent, bold = true },
    LazySpecial = { fg = c.sea },

    NvimTreeNormal = { fg = c.fg, bg = c.bg },
    NvimTreeWinSeparator = { fg = c.line, bg = c.bg },
    NvimTreeRootFolder = { fg = c.accent, bold = true },
    NvimTreeFolderName = { fg = c.soft },
    NvimTreeOpenedFolderName = { fg = c.sea },
    NvimTreeEmptyFolderName = { fg = c.muted },

    ["@comment"] = { fg = c.muted, italic = true },
    ["@keyword"] = { fg = c.accent },
    ["@keyword.function"] = { fg = c.accent },
    ["@string"] = { fg = c.sea },
    ["@number"] = { fg = c.warn },
    ["@type"] = { fg = c.soft },
    ["@type.builtin"] = { fg = c.sea_bright },
    ["@function"] = { fg = c.fg },
    ["@function.builtin"] = { fg = c.sea_bright },
    ["@variable"] = { fg = c.soft },
    ["@variable.builtin"] = { fg = c.warn_bright },
    ["@property"] = { fg = c.soft },
    ["@operator"] = { fg = c.soft },
    ["@punctuation"] = { fg = c.muted },
  }

  for group, opts in pairs(groups) do
    set(0, group, opts)
  end
end

return M
